site_name: mtd
repo_url: https://github.com/cits3200-team37/mtd
repo_name: cits3200-team37/mtd

theme:
  name: material
  logo: assets/logo_wide.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - Home: index.md
  - Code Review: codereview.md
  - Back End:
      - End points: backend/endpoints.md
  - MTD Network Code Base:
      - MTD:
          - MTD init: mtdnetwork/mtd/mtdinit.md
          - Complete Topology Shuffle: mtdnetwork/mtd/completetopologyshuffle.md
          - Port Shuffle: mtdnetwork/mtd/portshuffle.md
          - Host Topology Shuffle: mtdnetwork/mtd/hosttopologyshuffle.md
          - IP Shuffle: mtdnetwork/mtd/ipshuffle.md
          - OS Diversity: mtdnetwork/mtd/osdiversity.md
          - OS Diversity Assignment: mtdnetwork/mtd/osdiversityassignment.md
          - User Shuffle: mtdnetwork/mtd/usershuffle.md
          - Service Diversity: mtdnetwork/mtd/servicediversity.md
      - Operation:
          - Attack Operation: mtdnetwork/operation/attack_operation.md
          - MTD Operation: mtdnetwork/operation/mtd_operation.md
      - Component:
          - Host: mtdnetwork/component/host.md
          - MTD Scheme: mtdnetwork/component/mtd_scheme.md
          - Network: mtdnetwork/component/network.md
          - Service: mtdnetwork/component/service.md
      - Statistic:
          - Evaluation: mtdnetwork/statistic/evaluation.md
