name: Build/release

on: push

jobs:
  release:
    runs-on: ["${{ matrix.os }}", macos-13-xlarge]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            script_define: GITHUB_TOKEN=$PUBLISH_TOKEN
          - os: windows-latest
            script_define: set GITHUB_TOKEN=$PUBLISH_TOKEN &&

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        working-directory: client
        run: npm i
      - name: publish
        working-directory: client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ${{ matrix.script_define }} npm run publish
      - name: Macos arm setup
        working-directory: client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: GITHUB_TOKEN=$PUBLISH_TOKEN npm run publish
