name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      working-directory: client
      run: npm i
    - name: install electron forge
      run: npm i -g electron-forge
    - name: publish
      working-directory: client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      run: GITHUB_TOKEN=$PUBLISH_TOKEN npm run publish

